### ISSUE TITLE
Graphics card: Microsoft Basic Render Driver is blacklisted.

### ISSUE THREAD

**Issue by CMingTseng** [arkivanov/CompoSnake#1]
Dear Sir

i get this  

Graphics card: Microsoft Basic Render Driver is blacklisted.

at  ComposeSnake:desktop:run

THX

**Comment by arkivanov** [comment]
Hello @CMingTseng, I suggest to raise this issue in https://github.com/JetBrains/compose-jb, it looks like related to Compose for Desktop.
